
# SEO settings
title: "mrpnkt"
title2: "space" # default: ""
description: "Just some testing"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://mrpnkt.github.io/ # site url
#baseurl: ""  apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: # UA-XXXXX-XX
repo: http://github.com/heiswayi/thinkspace
disqus_shortname: # "heiswayi"
twitter_username: # "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "mrpnkt"
  job      : "problem solver"
  bio      : "eat, sleep, learn, die"
  thumb    : /images/author.jpg
  email    : mr@mrpnkt.com
  url      : http://mrpnkt.github.io
  github   : http://github.com/mrpnkt
  twitter  : http://twitter.com/mrpnkt
  facebook : # https://www.facebook.com/profile.php?id=666
  linkedin : http://linkedin.com/in/mrpnkt

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@mrpnkt"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
